# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planning/PoseWithUncertainties.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PoseWithUncertainties(genpy.Message):
  _md5sum = "143b13c3f79c2e2058bebcc4baee982a"
  _type = "planning/PoseWithUncertainties"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Quaternion position
geometry_msgs/Quaternion uncertainties

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['position','uncertainties']
  _slot_types = ['geometry_msgs/Quaternion','geometry_msgs/Quaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,uncertainties

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseWithUncertainties, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Quaternion()
      if self.uncertainties is None:
        self.uncertainties = geometry_msgs.msg.Quaternion()
    else:
      self.position = geometry_msgs.msg.Quaternion()
      self.uncertainties = geometry_msgs.msg.Quaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.position.x, _x.position.y, _x.position.z, _x.position.w, _x.uncertainties.x, _x.uncertainties.y, _x.uncertainties.z, _x.uncertainties.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Quaternion()
      if self.uncertainties is None:
        self.uncertainties = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.position.x, _x.position.y, _x.position.z, _x.position.w, _x.uncertainties.x, _x.uncertainties.y, _x.uncertainties.z, _x.uncertainties.w,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.position.x, _x.position.y, _x.position.z, _x.position.w, _x.uncertainties.x, _x.uncertainties.y, _x.uncertainties.z, _x.uncertainties.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Quaternion()
      if self.uncertainties is None:
        self.uncertainties = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.position.x, _x.position.y, _x.position.z, _x.position.w, _x.uncertainties.x, _x.uncertainties.y, _x.uncertainties.z, _x.uncertainties.w,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
