#!/usr/bin/env python

import time

import rospy
from std_msgs.msg import Int8

# battery
battery_level = 100

def main():
    global battery_level
    rospy.init_node('drone_placeholder')
    pub_batt = rospy.Publisher('drone/battery_level', Int8, queue_size=2)

    rate = rospy.Rate(10)
    t = time.time()
    while battery_level > -10 and not rospy.is_shutdown():
        t2 = time.time()
        if (time.time() - t) > 1:
            t = time.time()
            battery_level -= 1
            msg = Int8()
            msg.data = battery_level
            pub_batt.publish(msg)
            print(msg)
            rate.sleep()

    rospy.spin()

if __name__ == '__main__':
    print('drone started')
    main()
