// Generated by gencpp from file planning/PoseWithUncertainties.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_POSEWITHUNCERTAINTIES_H
#define PLANNING_MESSAGE_POSEWITHUNCERTAINTIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Quaternion.h>

namespace planning
{
template <class ContainerAllocator>
struct PoseWithUncertainties_
{
  typedef PoseWithUncertainties_<ContainerAllocator> Type;

  PoseWithUncertainties_()
    : position()
    , uncertainties()  {
    }
  PoseWithUncertainties_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , uncertainties(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _uncertainties_type;
  _uncertainties_type uncertainties;





  typedef boost::shared_ptr< ::planning::PoseWithUncertainties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::PoseWithUncertainties_<ContainerAllocator> const> ConstPtr;

}; // struct PoseWithUncertainties_

typedef ::planning::PoseWithUncertainties_<std::allocator<void> > PoseWithUncertainties;

typedef boost::shared_ptr< ::planning::PoseWithUncertainties > PoseWithUncertaintiesPtr;
typedef boost::shared_ptr< ::planning::PoseWithUncertainties const> PoseWithUncertaintiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::PoseWithUncertainties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::PoseWithUncertainties_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'planning': ['/home/mikael/project_ws2/src/planning/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning::PoseWithUncertainties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::PoseWithUncertainties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::PoseWithUncertainties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::PoseWithUncertainties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PoseWithUncertainties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::PoseWithUncertainties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::PoseWithUncertainties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "143b13c3f79c2e2058bebcc4baee982a";
  }

  static const char* value(const ::planning::PoseWithUncertainties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x143b13c3f79c2e20ULL;
  static const uint64_t static_value2 = 0x58bebcc4baee982aULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::PoseWithUncertainties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/PoseWithUncertainties";
  }

  static const char* value(const ::planning::PoseWithUncertainties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::PoseWithUncertainties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion position\n\
geometry_msgs/Quaternion uncertainties\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::planning::PoseWithUncertainties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::PoseWithUncertainties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.uncertainties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseWithUncertainties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::PoseWithUncertainties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::PoseWithUncertainties_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "uncertainties: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.uncertainties);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_POSEWITHUNCERTAINTIES_H
